### ISSUE TITLE
是否能增加文章标题和评论一起推送的功能呢

### ISSUE THREAD

**Issue by YomiPixel** [lscho/CommentToWechat_for_typecho#1]
这样应该会更直观吧……

**Comment by lscho** [comment]
[https://github.com/lscho/CommentToWechat_for_typecho/blob/master/Plugin.php#L59](https://github.com/lscho/CommentToWechat_for_typecho/blob/master/Plugin.php#L59)

这里已经有文章标题了，也有评论内容
